### ISSUE TITLE
Undo/Back button

### ISSUE THREAD

**Issue by alsoknownasdrew** [8values/8values.github.io#1]
It would be great if there was an undo button. I mean if I make a mistake I have to repeat all the questions, that's a huge pain in the ass :D

**Comment by TristanBomb** [comment]
I appreciate the suggestion, and there's a possibility that this might be implemented in the future. However, the current structure of the quiz does not track individual answers, only accumulated scores. As such, an undo button is currently impossible.

I apologize for the inconvinience.

**Comment by TristanBomb** [comment]
This is now implemented.
