### ISSUE TITLE
question 41 doesn't make sense?

### ISSUE THREAD

**Issue by syrup1-gt** [8values/8values.github.io#106]
"The stronger the leadership, the better."
does this mean the leadership is stronger, as more power, or as in the leadership is smarter/stronger willed?
(i.e. Robert E. Lee was a strong leader because he knew how to fight better than the union generals)

**Comment by Genora51** [comment]
Duplicate of #92.
See Tristan's answer regarding this question:

> The intent leans more towards "more powerful," but this question is intentionally vague, because the question is asking about your support for a particular mantra - "we need stronger leaders."
