### ISSUE TITLE
RUS: Я поддерживаю систему единоплательщика, общедоступную медицину.

### ISSUE THREAD

**Issue by denizzzka** [8values/8values.github.io#108]
непонятен этот вопрос
возможно, плохой перевод?

**Comment by Genora51** [comment]
Это может быть плохой перевод. Однако я думаю, что вы должны открыть это как проблему в [8values-ru](http://github.com/8values-ru/8values-ru.github.io), потому что они отвечают за перевод вопросов.

Возможно, лучший перевод будет:

    Я поддерживаю систему единоплательщика, всеобщего медицинского обслуживания

**Comment by denizzzka** [comment]
8values-ru? There is no way to create a ticket

**Comment by Genora51** [comment]
Then I'm not sure what the best option is, since we don't maintain the
Russian translation. Hopefully if I can make Version 2 ever happen then
internationalisation will be built in.
