### ISSUE TITLE
Stalinism-Maoism?

### ISSUE THREAD

**Issue by elifoster** [8values/8values.github.io#11]
What is Stalinism-Maoism? I have never heard this, and some comrades of mine were also really confused by seeing that in the ideology list. The only *-Maoism I have heard of is Marxism-Leninism-Maoism (MLM) which is pretty common.

**Comment by TristanBomb** [comment]
The goal is not to imply that there *is* an ideology called Stalinism-Maoism. Instead, the two ideologies are sufficiently similar such that they can't be distinguished by the quiz.

**Comment by elifoster** [comment]
I wouldn't say that they are very similar at all, though. Stalinism is mostly about "socialism in one nation" and totalitarianism, while Maoism is about achieving socialism through a people's army, vanguardism (origins in Leninism), and weakening the imperialist nations through third world revolution. There's a reason so many anarchists are into Maoism, but hate Stalinism.

**Comment by TristanBomb** [comment]
Mao was a totalitarian as well, and "vanguard parties" are often authoritarian in nature. While I definitely agree that there is a difference, it's too fine of a detail to be distinguished by a quiz that measures 4 numbers.
