### ISSUE TITLE
Collaboration with the test

### ISSUE THREAD

**Issue by TotalPolix** [8values/8values.github.io#114]
Hi,
I am a fan of your online political test 8values. I think it is pretty cool and accurate and it has a great potential.
Is there a way to help/collaborate with the Project?
I hope your answer.
Thanks, and have a nice day.

**Comment by Genora51** [comment]
If you like the project, feel free to fork the repository. If you have any changes, updates or cool new features you want to add to the project, make those changes in your personal fork.

Once you feel your additions are ready to be included in the real site, you can make a pull request so we can review your code and check it doesn't break anything.

If it all checks out, then your contributions will be added into the main repository! This is an open source project so of course we welcome collaboration.
