### ISSUE TITLE
anyone can alter the result 

### ISSUE THREAD

**Issue by naveenmultani** [8values/8values.github.io#115]
https://8values.github.io/results.html?e=59.0&d=61.1&g=54.0&s=53.3

url should be more sophisticated to show the result.

**Comment by ricealexander** [comment]
It may be worth noting that the page does not check whether the URL Values are within range:

https://8values.github.io/results.html?e=590&d=611&g=540&s=533

**Comment by ConnorWilloughby2** [comment]
Personally I would disagree that this needs to be restricted. @ricealexander is correct though.

**Comment by ten7ei** [comment]
I also don't see need for this. As long as you can take the test as often as you want you could also alter just your choices. 

However I agree if you really want to manipulate your result at least you have to "learn" what choices you have to make to get the result you want. The question is what is the goal of this quiz and in what way the change brings us closer to the goal.

**Comment by ConnorWilloughby2** [comment]
Personally i don't see the point in changing the logic, other that than the bug fix mentioned. 

This is simply a result page, it doesn't need to be anything else.
