### ISSUE TITLE
I've looked at the LICENSE copyright stuff and I'm wondering whether to change it to the current date or not.

### ISSUE THREAD

**Issue by darius-leong** [8values/8values.github.io#119]
I don't know much about copyright or anything like that, but I'm assuming that if I change it to the current year, that will screw it all up because the copyright license was issued only for that year. But if I'm wrong and copyright goes on forever or something along those lines, please tell me.

**Comment by SouthernWolf95** [comment]
It needs to be changed to the current year, yes. Please feel free to go ahead and do so

**Comment by Genora51** [comment]
Fixed.
