### ISSUE TITLE
The quiz mixes up “religious” and “traditional”

### ISSUE THREAD

**Issue by TVinSin** [8values/8values.github.io#120]
While there is a lot of correlation between conservatives and religious people. There are many right wing atheists

And a lot of the more tradition based results have "religious" or "theocratic" in the title. I think this could be inaccurate to some

**Comment by Genora51** [comment]
From the homepage:
> Those with higher Tradition scores believe in traditional values and strict adherence to a moral code. Though not always, they are usually religious, and support the status quo or the status quo ante.
While there are many right-wing atheists, a belief in traditional values and moral absolutism is strongly correlated with religious belief, and ideologies which hold these values strongly are often religious or theocratic in nature. I would hope that a right-wing atheist would find their beliefs more represented in the other axes; for instance if those views are conservative by economic standards then that should be reflected in the economic axis.
