### ISSUE TITLE
Add non-political views?

### ISSUE THREAD

**Issue by gordonel** [8values/8values.github.io#124]
Some non-political views may also influence one's viewpoint

Example:
"I don't like frequent software updates" if agreed to may indicate that the person is non-progressive, anti-security and traditional

Should such opinions be allowed at 8values?

**Comment by ricealexander** [comment]
I don't like frequent software updates. Windows gets super laggy anytime an update is pending, my banking app forgets my credentials sometimes after an update, and often after updates, my apps will ask for permissions I don't think they need. I don't match any of those traits you identified.

Non-answer aside, I think less-politically-specific questions might be beneficial.

**Comment by nissubjtsdjarwylwz** [comment]
>non-progressive
You wanted to say conversative.
> anti-security
You wanted to say liberal

> "I don't like frequent software updates" if agreed to may indicate that the person is non-progressive, anti-security and traditional
 
Or indicate that a person doesn't like being interrupted, doesn't like extra-hassle and to do extra things. And who defines what is progressive and conservative? It is a term subjective  to the society and used by polit-technologist to get young or old voters. In Russia right wing is progressive, in US left wing is progressive. Both wings are of the same age, defined in 19th century. However, historically, people never had human rights, especially in Russia - people in Russia never had freedom of speech and it's only 30 years as we have it with help of right winger politics,  and therefore Right Wing offering human rights is a relatively new shift,

**Comment by sagarreddypatil** [comment]
I want to add my view here - I don't like software updates in the popular sense, i.e., Windows Updates, so I switched to Linux which gives me more flexibility, so not wanting to perform updates could also be seen as progressive and liberal.

**Comment by 3rikk** [comment]
This dosen't really make much sense imo.
Authoritarians dont neccesarily want to be in bed with microsoft and get all the updates every day
Liberals dont neccesarily hate microsoft and want to use linux or something
etc etc

**Comment by Genora51** [comment]
Yes, while I think there are potentially valid questions which don't seem to have a political slant, I don't think this sort of question is particularly useful for assessing anyone's political views.
