### ISSUE TITLE
Ideology text clips into 8values text for some ideologies

### ISSUE THREAD

**Issue by TristanBomb** [8values/8values.github.io#13]
On the canvas image thing, some ideology names are long enough to clip into the "8values" title.

**Comment by Berkmann18** [comment]
Not sure, how far you've gone into solving this issue, but I'll still propose some solutions:
- Reducing labels to short and known versions (e.g: Social Democracy to SocDem, Anarcho-capitalism to ancap, ...).
- Moving the 8values bit in a responsive/dynamic way that it won't just sit there

**Comment by TristanBomb** [comment]
Actually, this bug was resolved recently. I forgot to close the issue, though! Whoops.

**Comment by Berkmann18** [comment]
Good thing I commented on this then :).
