### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ChickenHacker12** [8values/8values.github.io#132]
The focus states for buttons aren't visible enough.

**Comment by Genora51** [comment]
At the moment, I don't think the buttons even have focus states. Thanks for bringing this to my attention!

What would you suggest for improving accessibility (i.e. how should the focus states look)?

**Comment by ChickenHacker12** [comment]
They could just be a box-shadow with a [contrasting color](https://color.a11y.com) that relatively matches the button.
