### ISSUE TITLE
Issue with a question

### ISSUE THREAD

**Issue by PastelProgrammer** [8values/8values.github.io#133]
Why does the "Oppression by corporations is a larger threat than oppression by Governments" question increase your economic axis  but not your government axis? In my opinion, it should effect both. As it is possible for you to think "I think BOTH of them are an equal scale threat." when disagreeing with the question.

**Comment by Genora51** [comment]
Thanks for reminding me about this - pretty sure it has been raised before but I had totally forgotten to modify this, though I think it probably only warrants -5 on the civil axis because of the way the question is phrased.

**Comment by PastelProgrammer** [comment]
Alright, that works.
