### ISSUE TITLE
remove answer amplification

### ISSUE THREAD

**Issue by determin1st** [8values/8values.github.io#147]
from my ux

**Comment by Genora51** [comment]
Please elaborate, what would you like to be fixed?

**Comment by determin1st** [comment]
you have 5 answers: -2 -1 0 1 2 right? so -2 and 2 are amplifications of the same yes/no.. what is the meaning of amplification?

**Comment by Genora51** [comment]
The "strongly agree/disagree" answers (as I assume that's what you're referring to) are there to delineate how much you believe a certain statement, and are essential to the quiz. Take for example question 23:

> "Military spending is a waste of money."

Someone who believes military spending is too high and should be reduced (but that it is still important to have a military) might select `"Agree"`, whereas someone with more of a pacifist perspective who believes that militaries should be drastically reduced or abolished would more likely select `"Strongly Agree"`.

**Comment by determin1st** [comment]
nope, i disagree
