### ISSUE TITLE
"Goverment intervention is a threat to the economy" is not a usefull measure.

### ISSUE THREAD

**Issue by four18teapot** [8values/8values.github.io#154]
You can view this as a factually true statement without being against goverment intervention to the economy. This statement asks about descriptive views rather than prescriptive policies one would implement. This makes it too vague of a measure since you can agree to it from both sides of the spectrum.

**Comment by ConOLeary** [comment]
I have thought the same when answering this question.
What would you suggest as an alternative?
- perhaps _"Goverment intervention inhibits the economy from best serving the people"_?
