### ISSUE TITLE
Change "might/peace" to "nation/globe"

### ISSUE THREAD

**Issue by TristanBomb** [8values/8values.github.io#18]
The might/peace axis really measures nationalism versus cosmopolitanism, and the axis should be changed to reflect this.

**Comment by elifoster** [comment]
I think the usage of the term nation is confusing in this context. "Nation" generally speaking applies across nation-state borders. For example, African nationalism and Pan-Africanism are ideologies held by people of the African diaspora and people actually in Africa.

**Comment by TristanBomb** [comment]
Hm. Got a better term?

**Comment by elifoster** [comment]
nation-state maybe. I mean "nationalism" as a concept is pretty vague and has a lot of different meanings so you'll have to specify what kind of nationalism you're talking about.

**Comment by TristanBomb** [comment]
Done on the beta branch.
