### ISSUE TITLE
Deleonism & other ideologies don't really fit & aren't actually accessible via questions.

### ISSUE THREAD

**Issue by tadiou** [8values/8values.github.io#19]
Playing around with the data (and the ideology values), in order to get Deleonism, I have to answer a lot of questions that'd seem at odds with general syndicalist views.

```
   {
      "question": "The very existence of the state is a threat to our liberty.",
      "effect": {
         "econ": 0,
         "dipl": 0,
         "govt": 10,
         "scty": 0
      }
   }
```

Given that DeLeonism is `100/30/30/80`,  and DeLeonists are essentially syndicalists, and probably a lot closer to say, Anarcho-Syndicalists (at `80/50/100/80`) than Lenonism (`100/40/20/70`)....

DeLeonism's only real influence in the state isn't perpetuating existence of it, but in the deconstruction of it as a means to the end (which is where it differs from most anarchist types). But given the question suite at hand, it's much more difficult to grok that kind of nuance of what the purpose of the state is and more importantly differentiation between the state & union power, but to do that on 4 axes would be a bit more tricky.

DeLeonism is analogous to anarchist syndicalist tendancies only from a marxist perspective vs an anarchsit background, and all of those are relatively similar to left communism/socialism. I think it's a good distinction to have, but the amount of nuance & granularity you can get with the system in place necessarily allows the distinctions in place. Some of these based on the ideology numbers are better off grouped together & displayed that way (as a narrow, similar range).

Given a little bit of time, I might be able to do some combinatorial stuff to put together the possible questions in order to get to individual ideologies & could take a look if any of the combinations make sense. I was trying, to get `Religious Anarchism`, and in order to get that, you had to accede to significant number of state questions to drop the `govt` score to 0. And I think it's interesting that `Religious Socialism` isn't dovish (higher on the `dipl` scale), and it's harder when things are tied together like

```
{
      "question": "It is important that we work as a united world to combat climate change.",
      "effect": {
         "econ": 0,
         "dipl": 10,
         "govt": 0,
         "scty": 10
      }
   },
```

Where `dipl` & `scty` are tied together (I support the EU, Fascism, Absolute equality), it becomes markedly difficult for one to actually get the values required while maintaining reasonable applications of the question from the position given.

I've done it about 20-30 times and the ones I can get based on reasonable application of the questions are the Left-Lib ones, social democracy, progressivism, RW Populism, Liberalism, Moderate Conservativism, Reactionary, Capitalist Fascism, AnCap.

I had to bend the rules a bit to get Libertarianism & Moderate Conservatism (and it takes a while to do those because I have to keep a calculator because I haven't forked the source yet which I probably shoulda done first).

Anyway. Thanks for all the hard work on this, this ain't easy.

**Comment by tadiou** [comment]
I'll also possibly submit a PR once I sleep on it.

**Comment by TristanBomb** [comment]
Thank you for this analysis. I was noticing that some ideologies come up very rarely or not at all (although I have seen several people get non-capitalist Fascism), and some changes are in the works.
