### ISSUE TITLE
This is relevant.

### ISSUE THREAD

**Issue by Trendle** [8values/8values.github.io#22]
https://en.wikipedia.org/wiki/Right-wing_socialism

Just because I'm a socialist doesn't mean I'm a leftist. Just the fact that I answered the fascism question with "Agree" and it told me I'm a leftist is ridiculous.

**Comment by TristanBomb** [comment]
Socialism is near-universally considered a left wing ideology, especially when only considering the economy. Ideological matching will be improved soon, so perhaps when that's done you'll be happier with it?

**Comment by Trendle** [comment]
That's because right-wing socialism has been marginalized. Doesn't mean all socialists are leftists. As long as it doesn't tell me I'm a leftist I'm happy (I'm a simple man).

**Comment by TristanBomb** [comment]
The left-right axis is determined by economic positions, with socialism at the left and capitalism at the right. Conservative socialism is possible (equality+tradition) but right-wing socialism is not, as that would average out to the middle on the economic axis and thus no longer be socialism.

**Comment by Trendle** [comment]
I disagree.

**Comment by TristanBomb** [comment]
If the left is defined as socialism, how can it be possible to have right-wing socialism?

**Comment by Trendle** [comment]
No, you are defining it that way. There is no objectivity in that definition. Right-wing socialism is very possible, and it's been demonstrated both theoretically and practically.

**Comment by TristanBomb** [comment]
Well, I'm not sure what to tell you. Socialism is left-wing, and that's how I'm going to continue to define it.
