### ISSUE TITLE
Raised fist is not appropriate for authority.

### ISSUE THREAD

**Issue by KnightHawk3** [8values/8values.github.io#23]
https://en.wikipedia.org/wiki/Raised_fist

"The salute dates back to ancient Assyria as a symbol of resistance in the face of violence"

Perhaps an Eagle (used by many autocracies and fascist governments) would be a better solution?

**Comment by Saphareas** [comment]
An Eagle is also used by USA, Germany and other democracies, so maybe not that good. I would propose a crown, or maybe a surveillance cam like in 1984.

**Comment by TristanBomb** [comment]
Hmm, a crown implies hereditary monarchy. A gavel, perhaps?

**Comment by elifoster** [comment]
Maybe a marionette?

**Comment by TristanBomb** [comment]
This has been changed on the beta branch.
