### ISSUE TITLE
Questions relative to other people's views + more

### ISSUE THREAD

**Issue by Zefroo** [8values/8values.github.io#24]
Some of these questions just don't seem necessary and are a bad way of scoring people's values. The ones like "Communism/Capitalism/etc aren't as bad as people think" come to mind here. You're basically trying to score people's values based on what they think other people think. I've had a hard time answering this trying to come up with which "other people" is best to refer to in each case.
It also assumes people really understand these ideologies and what they stand for, which I think goes against the whole point of these quizzes which is to reveal what people's actual values are without the baggage of words that rile people up like "communism" and "capitalism".

Other issue: The question about terrorism, "Terrorism is a major threat, and some civil liberties must be sacrificed to prevent it," could be quite difficult to answer for the average person. Sure, logically it makes sense that if you disagree with the precedent and antecedent, you disagree with the whole thing (because of the and), but you should avoid assuming people understand that. A lot of people may think "well I do think terrorism is a major threat, but I'm not so down with surveillance, so I'm not sure how to answer this".
Possible suggestion: leave out the major threat part, something like "The sacrifice of some civil liberties is necessary to protect us from acts of terrorism".

**Comment by TristanBomb** [comment]
You're totally right, I'm removing those questions, and I've changed the terrorism question to match.
