### ISSUE TITLE
Phrasing on Statement/Question 33

### ISSUE THREAD

**Issue by okletzmayr** [8values/8values.github.io#26]
At the moment, statement 33 ("A strongly hierarchical state is most efficient.") is a bit vague if I understand it correctly.

One could agree that a state would be most efficient when organized in a hierarchical manner, but also believe that efficiency is not the most important thing to strive for in society.

One possible way to rephrase it would be something along the lines of  "A strongly hierarchical state is desirable", or "most efficient and therefore desirable" if you want it to be really verbose.

**Comment by TristanBomb** [comment]
This has been changed in the beta branch.
