### ISSUE TITLE
"Taxes should be increased on the rich to provide for the poor." assumes income taxation

### ISSUE THREAD

**Issue by faissaloo** [8values/8values.github.io#34]
I believe in wealth taxation, so I don't want to increase taxation (as a percentage anyway) but I also believe that money should be removed in larger amounts from the rich for the poor. The question should be rephrased to something like "More money should be taken from the rich to provide for the poor". Unless the writer means that the amount paid should be increased, rather than the percentage, in which case in needs more clarification such as "The percentage of tax paid should be increased on the rich to provide for the poor" coupled with an additional question: "The total amount of tax paid should be increased on the rich to provide for the poor".

**Comment by TristanBomb** [comment]
Don't those mean more or less the same thing?

**Comment by faissaloo** [comment]
You mean income and wealth taxation?

**Comment by TristanBomb** [comment]
"The percentage of tax paid should be increased on the rich to provide for the poor" and "The total amount of tax paid should be increased on the rich to provide for the poor" mean the same thing if the income of the rich doesn't change. Changing the quantity of money taxed also changes the percentage of money taxed.

**Comment by faissaloo** [comment]
*sigh*, that's true I guess we'll just have to find a better way of phrasing it. How about just straight up asking if people should be taxed based on income?
