### ISSUE TITLE
"Churches should be taxed the same way other institutions are taxed." assumes I want to tax other institutions

### ISSUE THREAD

**Issue by faissaloo** [8values/8values.github.io#35]
This needs an additional question asking whether or not I believe in taxing institutions separately from individuals.

**Comment by TristanBomb** [comment]
No, it doesn't. If you don't want to tax other institutions, and you don't want to tax churches, then you'd be taxing them the same way.

**Comment by faissaloo** [comment]
But I'm never asked if I want to tax other institutions.

**Comment by TristanBomb** [comment]
I should probably add this question, yes, but that doesn't affect the church question. It was specifically designed to be answerable by those who don't wish to tax any institutions - if you're not taxing either, you're taxing them in the same way, which is "not at all."

**Comment by faissaloo** [comment]
I understand that, I agree with you.

**Comment by TristanBomb** [comment]
Alright, cool. Have a nice day!
