### ISSUE TITLE
"Capitalist Fascism" is generally called "National Capitalism".

### ISSUE THREAD

**Issue by NukeRusich** [8values/8values.github.io#36]
There's a few other terms for it due to the fact there's a naming conflict between the AltRight and AltLite, but "National Capitalism" is still generally associated to anything that passes as Capitalist Fascism on this quiz (although you'll need to do "National Capitalism (ethnic/AltRight)" and "(civic/AltLite)" or something like that for v2).

**Comment by LukeStonehm** [comment]
"Capitalist Fascism" what an oxymoron. 

Capitalism == voluntary trading of goods/services for goods/services 
Fascism == forced coercion (often using violence) to a particular set of ideas.

**Comment by elifoster** [comment]
Luke neither of those are accurate definitions.

Capitalism: Private ownership of the means of production, industry exists to generate capital.
Fascism: Authoritarian right wing nationalism, often using racism and anti semitism as a uniting tool.

**Comment by LukeStonehm** [comment]
@elifoster yes sorry, I agree with both of those definitions. 

RE: fascism, I was more referring to authorianism in general, my bad.

My main point was that Capitalism is presupposed upon the principle of voluntary interaction -> a corporation cannot oppress you because you can choose not to do business with them.

This is incompatible with an authorianism system like fascism, hence why I think a term like "Capitalist Fascism" is an oxymoron.

**Comment by NukeRusich** [comment]
@LukeStonehm I believe you're confusing Capitalism and Libertarianism. 

@elifoster What about the suggestion?

**Comment by TristanBomb** [comment]
In regards to the rename: yeah, that'll probably happen in the ideology rework. The current system was pretty much just cobbled together, and I used whatever names I thought of at the time.

In regards to the "can capitalism be authoritarian" debate: it _absolutely_ can be (though it doesn't _have_ to be). Historically, there have been many instances of authoritarian capitalist regimes, many supported by the United States in the Cold War, such as Pinochet's Chile or Batista's Cuba. Capitalism _isn't_ voluntary interaction, it's "an economic system and an ideology based on private ownership of the means of production and their operation for profit," according to Wikipedia. Nothing involved there is incompatible with authoritarianism.
