### ISSUE TITLE
The opposite axes are not really opposite

### ISSUE THREAD

**Issue by grep0** [8values/8values.github.io#38]
The opposition to one side of the axis does not mean support of the other side.
For example, on the Nation/World axis, the opposition to the current international bureaucracy does not mean pro-nationalism.
On the Equality/Market axis, a sentiment against the power of market self-regulation should not be counted as pro-social.

**Comment by zachoooo** [comment]
> the opposition to the **_current_** international bureaucracy does not mean pro-nationalism.

It's a matter of principle, not a matter of the current situation. You can hate our current capitalist system, but still strongly support capitalism. Likewise you can still oppose organizations like the EU and UN, but still support international political efforts in principle. National focus and world focus are opposite in principle even if you may disagree with what the current reality is.

**Comment by TristanBomb** [comment]
Zachoooo is, for the most part, correct. Though there are a few questions about current institutions, they're by far a minority. The test is called 8values: it's about values, and there IS fundamentally a dichotomy between a cosmopolitan perspective and a nationalistic one.
