### ISSUE TITLE
Lacking a political ideology representing Objectivism

### ISSUE THREAD

**Issue by hsoj95** [8values/8values.github.io#40]
I was looking through the list of possible political ideologies that can be received by taking the test, and I noticed there was no listing for Objectivism. While it's not completely unsimilar to Libertarian Capitalist, or something like Anarcho-Egoism, Anarcho-Capitalism, or Market Anarchism, it definitely is different from these specific categories. It would be cool to see a specific option show up for Objectivist in the test. If you don't like, or don't want to use the term "Objectivist", then you could also call it "Rational Egoism", as that term represents the same philosophy as does the term Objectivist.

I can provide more information if necessary, but I can give a sorta easy way to think of it. If Libertarianism is an umbrella term, then Objectivism is a specific kind of Libertarianism, although most Objectivist reject this idea simply because of the implication of being conflated with Libertarians.

**Comment by hsoj95** [comment]
I have started adding in an ideology that fits roughly into what Rational-Egoism would be identified with on the axis. Based on my preliminary tests for the new ideology I added, Rational-Egoism will come above the other market centered ideologies, but will come just below Anarcho-Capitalism, namely based on the economic and government scale.

In the process of doing this, I have noticed some odd peculiarities as to how the ideology matching works, specifically with regard to how each axis is used to determine which ideology is matched. I have noticed some axis have a strong pull on the matching than others, namely the economy axis. Anyone know if this is by design, or just a quirk of the way the calculations are done?

**Comment by TristanBomb** [comment]
This came up in a more recent thread, but for the sake of documentation, I will confirm that the economy and civil axes *do* have a stronger effect on ideology matching than the diplomatic and society axes. This is because ideologies tend to have strong positions on the economy and role of government. The other axes vary wildly in their importance; the diplomatic axis is quite influential in the authoritarian far-left, but less so among the right. The opposite is true of the society axis.

An eventual ideology rework will probably do matching via different means, where weighting can hopefully be determined on a per-ideology basis.

**Comment by hsoj95** [comment]
That's really interesting! Thanks for sharing that! That explains why when I was playing around with adding Objectivism/Rational-Egoism as an option, the diplo axis had literally no affect at all!

**Comment by hsoj95** [comment]
I have added an ideological match for Rational-Egoism to the JS file! It may take a bit of fine tuning to be exactly right, but it should work well for the niche of people that fall into that category!

**Comment by hsoj95** [comment]
From #58:
> And as an anarchist, I can tell you that "libertarian" and "anarcho" (for us) are used synonymously.

This is why I was saying there needs to be a separate ideological match for Rational-Egosim/Objectivism! Even though Libertarianism and Objectivism can be very similar politically, with some even calling Objectivism a branch of Libertarianism, the vast majority of Objectivist will refuse to identify, or be identified, with Libertarians, because of the very sentiment expressed in the quote above.

**Comment by Genora51** [comment]
(Added in latest commit)
