### ISSUE TITLE
There should be a link on the front page back to the GitHub page

### ISSUE THREAD

**Issue by hsoj95** [8values/8values.github.io#42]
I noticed that on the front page of the test, there is no link back to the main GitHub page for the project. This means the only way to find the GitHub page from the test itself is to go and search GitHub to find it. Not overly hard, but somewhat inconvenient. All that needs to be added is a simple hyperlink back to the GitHub page somewhere near the bottom of the page.

I'd be happy to add it to save y'all the trouble if you'd like me to. :)

**Comment by hsoj95** [comment]
Ok, I added the links to two specific sentences where the email link is also shown and where comments and criticism are asked for. Specifically on the index (Front page) and the results page.

However, I am having issues submitting a pull request for my commits. Anyone know a simple procedure for doing so? (I'm not very experienced with GitHub I'm afraid, but I do know HTMl, CSS, and JavaScript well!)

**Comment by hsoj95** [comment]
I forked the project and added the links to the appropriate locations on the index (front) page and the results page.

The pull request has been sent and is awaiting approval! :) #43

**Comment by TristanBomb** [comment]
Since your PR has since been merged, I'm going to close this now :)
