### ISSUE TITLE
Updated labels in values.svg have missing/different fonts

### ISSUE THREAD

**Issue by Volvagia356** [8values/8values.github.io#44]
The updated labels for "Markets", "Nation", and "World" in values.svg seem to be using a different font from the other labels, or not have a font set entirely.

![2017-05-11-024555_879x492_scrot](https://cloud.githubusercontent.com/assets/1742810/25915451/10c6cc1c-35f4-11e7-8b1d-43b020fb8a3f.png)

**Comment by hsoj95** [comment]
That's an interesting discovery, I didn't notice this before! I actually think I like the labels for Markets, Nation, and World better, but I also know that sans-serif fonts look better on digital displays, especially smaller sized ones. So with that being said, they all probably need to be the same sans-serif font. I believe if I remember right it was the Google Font "Montserrat" used in the HTML code, but I'm not sure that is the font used in the SVG's. Looks the same to me, but that's not always easy to tell with sans-serif fonts.

**Comment by Saphareas** [comment]
This won't be an issue anymore, when the localization PR is finally merged, as the text will be rendered seperatly.

**Comment by TristanBomb** [comment]
Is this still an issue? I've checked the files for those particular icons, and they use SVG paths rather than text. Perhaps I fixed this without closing the issue?

In any case, I would appreciate it if someone who didn't have Montserrat installed checked this.

**Comment by hsoj95** [comment]
No, it's definitely still present when I check from an iMac that doesn't have Monserrat installed! You can see [here](https://imgur.com/a/4ptcU)

**Comment by TristanBomb** [comment]
Aha! The _individual_ icons for the 8 ideologies are fine, it's the _combined_ image that doesn't work. Would you mind checking again to see if it's resolved?

**Comment by hsoj95** [comment]
yes indeed! It is now fixed! I'll close the issue for ya! :)
