### ISSUE TITLE
Question 56: Bias in term?

### ISSUE THREAD

**Issue by 4of92000** [8values/8values.github.io#45]
Question 56 reads "Same-sex marriage should be legal." This inadequately represents those who oppose the adoption of same-sex marriage as such, since most do not believe that it should be illegal, but rather that the terms "same-sex" and "marriage" are a contradiction in terms.

The question should read "Same-sex marriage should be legally recognized."

**Comment by brmbrmcar** [comment]
The real problem is for people who oppose marriage altogether.

(Also I hate to say this here but anyone who really thinks that 'same-sex' and 'marriage' contradict is an idiot in the kindest possible terms)

**Comment by 4of92000** [comment]
Glad to know I'm an idiot. See you on the interwebs.

**Comment by Berkmann18** [comment]
@brmbrmcar Agreed, same-sex isn't an opposing term to marriage which is literally just a contracted union between two people.

**Comment by TristanBomb** [comment]
Agreed. There's no contradiction here - if you don't believe same-sex marriage should be legally recognized, you implicitly believe that it should be illegal. Closing.

**Comment by 4of92000** [comment]
I very much beg to differ.

There is a difference between "legal" and "legally recognized". Illegal
means you shouldn't do that. Legally unrecognized means the state doesn't
say it's a thing. An example: If walked into the local JoP office and
filled out papers to marry my car, the clerk at the desk would look at me
funny and throw away the papers after I left, but I wouldn't be arrested:
it's not *illegal* to marry a car; it's*legally unrecognized. Marrying my
cat is not illegal because it's not a thing.

I (being the last backwards-assed Christian Right hick numbskull still
active on GitHub) do not think that gay marriage should be illegal. I
personally don't believe same-sex relationships should be illegal -- that
sure as hell isn't the government's job. I just don't think that "gay" and
"marriage" are compatible terms.

If you disagree with me (which you very obviously do), I'm not going to
force you to change your mind. First, I can't; second, that would be a
fabulous dick move. But I'm clarifying the position that I and people of
like mind hold.

And since this is a test of political values held and not an attempt to
foist one's values on other people through clever wordplay, it would be in
the best interest of your project to change the wording of the question to
make it less misleading.

**Comment by 4of92000** [comment]
Dammit, Gmail reply, stop putting carriage returns in weird places.

**Comment by brmbrmcar** [comment]
If it isn't a thing it can't be legal, or illegal.

**Comment by 4of92000** [comment]
Exactly, and since marriage traditionalists like myself believe the terms
"homosexual" and "marriage" contradict and that everyone else is
misdefining marriage, they believe it shouldn't be legally recognized.
That's why if you read publications by such groups, you'll typically see
the phrase "gay 'marriage'", complete with internal quotes.

Again, I do not expect you to agree with me. I do not even expect you to
find my position intelligent (though I of course think it is).

I am merely stating what my position is and saying that the 8values test as
it stands misrepresents it.

Please reword the question.

**Comment by brmbrmcar** [comment]
Logically from that though you'd put disagree, because it can't be legal or any part of the law at all.

**Comment by 4of92000** [comment]
"Legal" implies "legally permitted", not "legally recognized". I personally
don't care whether two men jump a broomstick in their backyard and then
sodomize each other all night; the question is whether the state should
accept that relationship as meeting the criteria for marriage. It's legal;
whether it should be legally recognized is up for grabs.

I don't see why it's so hard to add a dozen characters to that question.
This is JavaScript; there's no compiler to break, is there?

On Feb 6, 2018 09:51, "brmbrmcar" <notifications@github.com> wrote:

Logically from that though you'd put disagree, because it can't be legal or
any part of the law at all.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/8values/8values.github.io/issues/45#issuecomment-363465468>,
or mute the thread

**Comment by brmbrmcar** [comment]
Well I couldn't change it anyway.

**Comment by 4of92000** [comment]
Fair.

Should probably just make a pull request at this point.
