### ISSUE TITLE
How many questions? And a approximate time duration...

### ISSUE THREAD

**Issue by jerryasher** [8values/8values.github.io#46]
Looks like an interesting survey, but I won't do open ended surveys.

Is it 10 questions, 50, 100? And how long should it take?

You may wish to inform your visitors.

**Comment by elifoster** [comment]
Estimated time would be difficult because not everyone has the same understanding of English and it is currently not localized for any language but English.

The number of questions could be useful and simple, so I agree there.

**Comment by hsoj95** [comment]
I agree as well with @elifoster that it would not be really feasible to give an estimated time to complete the test. However, it would generally be fairly easy to show the number of questions in the test, either statically (not a good idea) or dynamically based on the questions in the JavaScript file.

**Comment by hsoj95** [comment]
I have added a line onto the front page that dynamically shows the number of questions currently in the survey. You can see it in the pull request here: #43

**Comment by Berkmann18** [comment]
This should be closed no?
The current master version inform the user how close he/she is from finishing the quiz>
Regarding time estimation, that would be hard (especially with the few ambiguous questions).

**Comment by TristanBomb** [comment]
You're correct, this has been implemented. Closing.
