### ISSUE TITLE
Value axes collection omnibus thread

### ISSUE THREAD

**Issue by no-identd** [8values/8values.github.io#55]
I figured it might make sense to have an issue that collects all known value axis used by other models, to offer something to reflect against for further improvements.

For example, http://www.abtirsi.com/quiz2.php uses 5 value axes. which I'll quote here:

- Collectivism
- Authoritarianism
- Internationalism
- Tribalism
- Liberalism

Explanation key: 

- Collectivism refers economic intervention, whether the society or state should intervene in the economy to redistribute wealth from the more to the less successful. The negative percentages indicate opposition to such intervention. 

- Authoritarianism refers to state power to control the actions of individuals to prevent them from harming others or themselves, and also to establish the will of the majority over society. Negative percentages indicate opposition to state power. 
 
- Internationalism refers to political involvement in other nations or global affairs, either via war, treaty or international organizations. Negative percentages indicate isolationist beliefs, and the belief in national sovereignty. 
 
- Tribalism refers to identity or nationalism, favoring your own nation over foreigners. Negative percentages indicate opposition to national or ethnic identity and oriented towards pan-humanism. 
 
- Liberalism refers to acceptance of historically illegal or immoral social practices or customs. Negative percentages indicate opposition to such acceptance.

**Comment by TristanBomb** [comment]
Sorry for the incredibly late response!

It's definitely interesting to see other models. Unfortunately, the project name has somewhat limited the number of possibilities (and it might be bad for branding to rename the project).

In any case, this is a good place to propose a system that relied on just three "philosophies" of governance - focus on society ("societalism" for lack of a better term), focus on the individual ("individualism"), and focus on authority ("authoritarianism").
-  Societalism is the idea that the chief purpose of government is to serve society as a collective.
Examples:
   - Taxing the rich to provide for the poor
   - Regulations to protect the environment
   - Using state funds on scientific research
- Individualism is the idea that the government should take a minimal role in individuals' lives.
Examples:
   - A deregulated market and laissez-faire capitalism
   - Liberal democracy with strong civil rights
   - Pacifism
- Authoritarianism is the idea that certain institutions, including governments, justify their own power.
Examples:
   - Support for dictatorships or absolute monarchy
   - An emphasis on strict moral codes (often religious in nature)
   - Militarism or territorial expansion

Most people have beliefs from all three philosophies, and most ideologies include a mixture of them. However, they are also going to be in different proportions. Market liberals will be mostly individualist, progressives will have both individualist and societalist beliefs, socialists will have mostly societalist beliefs, Marxist-Leninists will have both societalist and authoritarian beliefs, fascists will have mostly authoritarian beliefs, conservatives will have both individualist and authoritarian beliefs, and so on.
