### ISSUE TITLE
"Libertarian communist" doesn't fit in image output

### ISSUE THREAD

**Issue by brion** [8values/8values.github.io#56]
I got "libertarian communist", but the first two letters of "libertarian" overlap with the "8values" header:

![img_1300](https://user-images.githubusercontent.com/103075/28756299-7ff56f24-7520-11e7-8a5f-88ecf2ade0b7.PNG)

Tried in Safari on an iPad running iOS 11 beta 4.

**Comment by carlomontagnino** [comment]
same for “Moderate Conservatism”

**Comment by hsoj95** [comment]
Yeah, this has been an issue for a while now. Probably something in the font settings needs to be changed. I'll see if I, or one of the other contributors, can help fix this.

**Comment by TristanBomb** [comment]
I'm going to see if I can rework the canvas here a bit. I'm also going to include a test version number, so that future updates won't "break backwards-compatibility," so to speak.
