### ISSUE TITLE
Possible mistake in value scores

### ISSUE THREAD

**Issue by LuckyStampede** [8values/8values.github.io#57]
https://github.com/8values/8values.github.io/blob/master/questions.js#L231

This seems to be an error, because it doesn't make a whole lot of sense for international cooperation on research to **decrease** one's final "World" score. If there is a good reason for this, or an artifact of a previous iteration, it might be a good idea to reword this question.

**Comment by TristanBomb** [comment]
Er, yes, that is a mistake actually. Oops!

**Comment by TristanBomb** [comment]
Fixed.
