### ISSUE TITLE
Add Radar plot.

### ISSUE THREAD

**Issue by aberlin** [8values/8values.github.io#59]
It would be cool if one could see or in the best case compare test results as radar plots.[(Wikipedia)](https://en.wikipedia.org/wiki/Radar_chart). There are already nice libraries for stuff like this[(Example)](http://www.chartjs.org/docs/latest/charts/radar.html).

**Comment by ibnuda** [comment]
Interesting. But in this 4 dimensional chart, how should the information be presented?
This is an example from a random data set.
![something like this](https://user-images.githubusercontent.com/8169908/31129498-ebaee5ba-a87e-11e7-8847-e1dbf7ecd023.png)

**Comment by TristanBomb** [comment]
Since you've referred to this in the more general #60, I'm going to close this now.
