### ISSUE TITLE
Cannot download the final image on mobile browser

### ISSUE THREAD

**Issue by gervasiocaj** [8values/8values.github.io#7]
The bottom image at the end cannot be long-clicked to download, and there is no specific button for it either. Tested in Chrome for Android and MIUI Browser.

**Comment by TristanBomb** [comment]
This occurs because the final image is a canvas element. I'm aware of the problem but unfortunately I don't know how to fix it! If anyone knows, feel free to contact me or put in a pull request.

**Comment by slig** [comment]
> This occurs because the final image is a canvas element 

A suggestion: have an `img` overlay the canvas and then:

    overlayImg.src = canvas.toDataURL();

**Comment by brion** [comment]
Ran into this on mobile Safari too; the above suggestion sounds legit, should work. :)
