### ISSUE TITLE
Terminology is messed-up

### ISSUE THREAD

**Issue by giogziro95** [8values/8values.github.io#77]
[Here are my results.](https://8values.github.io/results.html?e=40.9&d=63.3&g=74.2&s=70.9)

I think it, on _Civil Axis_ it should say "libertarian" ([civil libertarianism](https://en.wikipedia.org/wiki/Civil_libertarianism)) rather than "liberal". Libertarianism is the opposite of authoritarianism in the political philosophy. Also, in "Closest Match", I'd expect to see "liberalism" or "classical liberalism". Libertarianism is a political philosophy with no distinct set of policies (some libertarians are anarchists, some aren't; some are left-leaning, some are right-leaning); it's not an ideology on its own.

Is the test using US terminology where "liberal" means centre-left and "libertarian" means liberal?

**Comment by brmbrmcar** [comment]
Liberal must mean centre-left (centre truthfully), because being left wing is the same as being libertarian.

**Comment by giogziro95** [comment]
@brmbrmcar According to what? [Liberalism](http://www.iep.utm.edu/polphil/#SH3a) is centrist (culturally, it's left-leaning while economically, it's right-leaning). [Libertarianism](](http://www.iep.utm.edu/libertar/)), as a term, is somewhat ambiguous, but often it's synonymous with anti-authoritarianism, so it isn't either left- nor right-leaning; it just means opposing all or some forms of authority. One can be libertarian and culturally and/or economically right-leaning, left-leaning or some combination of them.

**Comment by brmbrmcar** [comment]
It shouldn't just say libertarianism. I agree.

**Comment by TristanBomb** [comment]
For what it's worth, I'm using liberal and libertarian in two different senses. The first is on the civil axes, where the values are as follows: Anarchist-Libertarian-Liberal-Moderate-Statist-Authoritarian-Totalitarian. Thus, this is referring to "civil" liberalism and libertarianism. These terms are also used for ideologies, where "liberal" is considered generally centrist, and "libertarian" depends on the qualifying adjective.

**Comment by giogziro95** [comment]
@TristanBomb Interesting classification. I thought it was meant to refer civil libertarianism as one of two options.
