### ISSUE TITLE
"Inheritance and capital gains are legitimate forms of wealth."

### ISSUE THREAD

**Issue by ggvaldez** [8values/8values.github.io#8]
I believe those two could be separated as Inheritance and Capital Gains can be completely different subjects to some Social Libertarians, also some circles argument that Inheritance is anti-free-market/meritocracy, whilst Capital Gains are pro-free-market/meritocracy. Maybe this question could be only about Capital Gains?

**Comment by TristanBomb** [comment]
Someone's persistent :)

I'd be interested in hearing others' feedback on this question.

**Comment by elifoster** [comment]
>others' feedback
For leftists, this isn't really an important thing to distinguish since we consider neither to be legitimate forms of wealth.

**Comment by gabrielgrant** [comment]
Was sent this by a friend earlier today. Here's what I replied:

"This is cool. Interesting choice of axes. seems mostly accurate, and more nuanced than the political compass. A couple of the questions seemed kinda stupid. Especially the one that treated inheritance and capital gains as though they were equivalent"

**Comment by TristanBomb** [comment]
Alright, alright, I'll change it :)

**Comment by gabrielgrant** [comment]
Cool, thanks! As I said, other than that -- great job!

Would be awesome to also have an "about" page to learn a bit more about yourself, motivations, inspiration, how you came up with the questions etc.

**Comment by TristanBomb** [comment]
Maybe. Version 2 is going to focus on more technical changes to improve the accuracy of the test, but a more detailed analysis isn't a bad idea.
