### ISSUE TITLE
Ambiguous Question: foreign citizens and citizens within borders.

### ISSUE THREAD

**Issue by Legendsmith** [8values/8values.github.io#81]
"Governments should be as concerned about foreign citizens as they are about those within their borders."
This question is a little ambiguous. Is it citizens of foreign nations, or citizens of a nation who are living in other countries?

If the latter, consider rewording to: ``Governments should be as concerned about their citizens abroad as they are about those within their borders.``
If the former: ``Governments should be as concerned about foreigners as they are about their own citizens``

**Comment by TristanBomb** [comment]
Good idea. The intention is the former interpretation.
