### ISSUE TITLE
Disturbing question about automation

### ISSUE THREAD

**Issue by carlitoselmago** [8values/8values.github.io#90]
I find the question "A better world will come from automation, science, and technology." disturbing.
Feels like an impossible question to answer, beyond science and technology, automation as seen in 2018 could be seen as a nightmare or a salvation depending on the taxation of it. I think you could ask this question at the begining of 20th century and still feel the same. I think just by changing the "will come" with "could come" could fix this.

**Comment by SouthernWolf95** [comment]
No, the taxation of automation (which isn't going to happen) isn't the point of this question. This is just to gather the overall sense of what a user would feel about this topic. For example, myself being a Transhumanist, I would answer strongly yes to this question. Where as a hardline communist or even a religious fundamentalist would most like disagree in some form.
