### ISSUE TITLE
Social Democracy too authoritarian

### ISSUE THREAD

**Issue by JustAnotherGitHubUser468** [8values/8values.github.io#91]
I mean, it's change brought on by a democratic and peaceful government, rather than a dictator government, which it actually opposes. I think SD should be 60-70 in liberty, not 60 in authority.

**Comment by SouthernWolf95** [comment]
Well, I guess this sorta comes down to if this is supposed to be based in principle or reality. In principle SD's should be peaceful, but in reality quite a few SD governments/parties carry a rather authoritarian streak to them. Look to the SDP in Germany and Labour in Britain for examples of what I'm talking about.

**Comment by TristanBomb** [comment]
This was an error on my part, that I've just fixed. There were a couple instances where I entered the inverse value compared to what I intended, and it seems this was one of them.
