### ISSUE TITLE
Two almighty confusing questions

### ISSUE THREAD

**Issue by RainOfPain125** [8values/8values.github.io#92]
"Traditions are of no value on their own."
What is this even supposed to mean? 'no value on **their own**'? If it's confusing enough for me to ask, then maybe the question should be re-worked / re-worded :L

"The stronger the leadership, the better."
This questions especially confused me. Are you trying to ask if stronger leaders IE more capable and able ones would be better for everyone? Or do you mean stronger, IE more powerful?

**Comment by Genora51** [comment]
Closing because this seems to have been answered satisfactorily.

**Comment by Hofkey** [comment]
Just saw this thread and the second answer is horrible. It does not answer anything. So here I am giving you a definition, this definition of "strong leadership" is the most common one I found.

"Strong leadership is when you can encourage, motivate, inspire and challenge your team to produce their best work. Strong leadership connects a team together through a common purpose and builds relationships in the workplace that allow for effective communication, more creativity and better problem-solving skills"
