### ISSUE TITLE
Entire project is devastatingly stupid

### ISSUE THREAD

**Issue by twome** [8values/8values.github.io#99]
Nothing more to be said.

**Comment by Mikotochan** [comment]
I read this as "I didn't like my results".

**Comment by twome** [comment]
No, the core assumptions of the project are **entirely** arbitrary. Most of the quiz's design is utterly nonsensical.

- "Wealth"? For whom? Through what process? Is this measured by social inequality, material usefulness, monetary wealth? Who doesn't want "wealth"? How is this wealth produced?
- "Peace"? Peace under what conditions? What qualifies as war or violence - is structural/state violence and repression "peaceful"?
- "Progress"? Progress in what direction? Along which dimensions? How is progress evaluated? 

All this quiz determines is what answers people give to this specific quiz. You're either incredibly ignorant about basic sociological/politics concepts such as the Overton window, subjectivity/objectivity, test design, and linguistic framing / "leading questions", **or** you're deliberately being dishonest by disguising your subjective worldview as somehow objective & "testable". You're either a dilettante or a liar, and in whichever case, your blatantly conservative ideology seeps from every pore of this project. You're a fucking moron.
